/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published agents
         * @description One row per agent, its newest published version, unless every version is asked for. A version is immutable: the identifier is the digest of the definition's content, so the text a run was pinned to can always be read back.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate counts over runs
         * @description Counts every run that matches, not just the page a list would return. The console shows these figures as facts, so they are computed where the whole set is — never derived from a page.
         */
        get: operations["getRunStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs per hour, split by what became of them
         * @description Runs are bucketed by the hour they started and counted under the phase
         *     they are in now. That is the honest reading of "how is today going": a
         *     run that started at nine and is still waiting belongs to nine o'clock
         *     and to the waiting column, not to whenever it eventually ends.
         *
         *     Hours with no runs are absent rather than zero. The caller chose the
         *     period and knows which hours it covers.
         */
        get: operations["getThroughput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the Gate has decided, most recent first
         * @description Every effect passes the Gate, and this is that record read across runs
         *     rather than down one. It is how somebody sees whether the
         *     installation's rules are doing anything: a feed of nothing but
         *     "allowed" says the policy is not engaging, and a run of escalations on
         *     one rule says it is engaging too much.
         *
         *     Each entry names the rule, never a category. "Denied by policy" tells
         *     a reader nothing about what to change.
         */
        get: operations["listDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the run's ledger trail
         * @description Returns the run's steps in order. This is the audit trail: every entry
         *     is immutable and sealed into a hash chain, so the same request always
         *     returns the same bytes for the same range.
         */
        get: operations["listRunSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/steps/{seq}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the content a step references
         * @description Resolves the reference a step carries — the proposed tool arguments, a
         *     tool result, the run's input — and returns the bytes.
         *
         *     This is deliberately a second request. The trail is read constantly and
         *     by many people; the content behind it routinely carries personal data,
         *     so it is fetched only when someone opens the step that needs it. The
         *     digest lets the caller prove the bytes are the ones the chain sealed.
         */
        get: operations["getStepContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify the run's hash chain
         * @description Walks the chain and reports whether every link is intact. Used by the
         *     signed export and by the tamper alarm.
         */
        post: operations["verifyRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The approval inbox */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a suspended action */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consumption rolled up over a period
         * @description The run is the accounting unit; company, area and agent are dimensions
         *     derived from it. Totals always reconcile because they are projections
         *     of the same ledger rows.
         */
        get: operations["getCostRollup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every tool the platform knows, and what it is classified as
         * @description Tools arrive from their servers classified read-only whatever the server claims about itself. Promoting one is a separate, recorded act.
         */
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tools/{toolId}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record what a tool does to the world
         * @description The single point where write access enters the platform. The ruling is durable and attributed; the previous one is not amended, it is superseded, and both stay in the administrative trail.
         */
        put: operations["classifyTool"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the platform is configured to talk to
         * @description Tool servers and model providers. Credentials are never returned; a provider only reports whether one is stored.
         */
        get: operations["listIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/integrations/mcp-servers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Configure a tool server
         * @description Adding a server changes what agents can do, so it is recorded like any other administrative change. The tools it offers still arrive classified read-only; promoting one stays a separate act.
         */
        put: operations["putMCPServer"];
        post?: never;
        /** Remove a tool server */
        delete: operations["deleteMCPServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/integrations/providers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configure a model provider */
        put: operations["putModelProvider"];
        post?: never;
        /** Remove a model provider */
        delete: operations["deleteModelProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The ceilings configured per scope
         * @description A scope ceiling is a limit over a window, distinct from the per-run ceiling in an agent's specification. Both are enforced by the same check; a run is bounded by whichever binds first.
         */
        get: operations["listBudgets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/budgets/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set a scope's ceiling
         * @description Ceilings inherit downwards and never widen: an area cannot raise what its company allows. Reaching one pauses the run resumably rather than ending it, so raising the ceiling continues from the same step.
         */
        put: operations["putBudget"];
        post?: never;
        /** Remove a scope's ceiling */
        delete: operations["deleteBudget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What operators changed about the platform
         * @description The run ledger records what agents did; this records what people did to the rules agents run under. Append-only.
         */
        get: operations["listAdminEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem detail. */
        Problem: {
            /** @default about:blank */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        /** @enum {string} */
        Phase: "unstarted" | "running" | "awaiting_approval" | "awaiting_tool" | "parked" | "finished";
        /** @enum {string} */
        Verdict: "allow" | "constrain" | "require_approval" | "block";
        /**
         * @description What a tool does to the world. The domain's `unknown` is deliberately absent: it is the zero value that makes an unclassified tool fail closed, never something a caller may assert.
         * @enum {string}
         */
        Effect: "read" | "write" | "destructive" | "financial";
        /** @enum {string} */
        StepKind: "run_started" | "planned" | "gate_decided" | "budget_reserved" | "tool_called" | "tool_returned" | "budget_reconciled" | "approval_requested" | "approval_decided" | "compensated" | "failed" | "parked" | "run_finished";
        Scope: {
            company: string;
            area: string;
        };
        /**
         * @description Cache tokens are reported separately from input tokens: a cache read
         *     costs a fraction of the price, and without the split an expensive agent
         *     cannot be diagnosed.
         */
        Cost: {
            /** Format: int64 */
            micros: number;
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            /** Format: int64 */
            cacheReadTokens?: number;
            /** Format: int64 */
            cacheWriteTokens?: number;
        };
        Run: {
            runId: string;
            scope: components["schemas"]["Scope"];
            agentId: string;
            /** @description The specification version the run is pinned to. Publishing a new version never affects a run already in flight. */
            versionId: string;
            onBehalfOf?: string;
            phase: components["schemas"]["Phase"];
            /**
             * Format: int64
             * @description Sequence number of the last recorded step.
             */
            seq: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
            cost: components["schemas"]["Cost"];
            /**
             * Format: int64
             * @description Outstanding reservations not yet reconciled.
             */
            reservedMicros?: number;
            /** @description Accumulated data-flow labels of the run context. */
            labels?: string[];
            pendingApproval?: components["schemas"]["PendingApproval"] | null;
        };
        Tool: {
            /** @description Namespaced by server, because two servers naming a tool "search" must not collide into one capability. */
            toolId: string;
            server: string;
            description?: string;
            effect: components["schemas"]["Effect"];
            untrusted: boolean;
        };
        MCPServer: {
            /** @description Namespaces the tools it offers, so two servers naming a tool "search" do not collide. */
            name: string;
            command: string;
            args?: string[];
            enabled: boolean;
            updatedBy?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ModelProvider: {
            name: string;
            /** @enum {string} */
            kind: "anthropic" | "openai_compatible";
            baseUrl: string;
            enabled: boolean;
            /** @description Whether a credential is stored. The credential itself never leaves the vault through this API. */
            hasKey: boolean;
            updatedBy?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ScopeBudget: {
            /** @enum {string} */
            scopeKind: "installation" | "company" | "area";
            scope?: components["schemas"]["Scope"];
            /** @enum {string} */
            period: "daily" | "monthly";
            /** Format: int64 */
            micros?: number;
            /** Format: int64 */
            tokens?: number;
            /** Format: int64 */
            toolCalls?: number;
            /** Format: int64 */
            steps?: number;
            /** Format: int64 */
            wallClockMs?: number;
            enabled: boolean;
            updatedBy?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminEvent: {
            /** Format: date-time */
            at: string;
            principalId: string;
            scope?: components["schemas"]["Scope"];
            /** @description Past tense, namespaced by what it touched — tool.classified, provider.created. */
            action: string;
            target: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        Agent: {
            agentId: string;
            /** @description The digest of the definition's content. Publishing new text is a new version; the old one stays readable. */
            versionId: string;
            scope: components["schemas"]["Scope"];
            name: string;
            provider: string;
            model: string;
            effort?: string;
            /** @description The capability pack resolved to concrete tools. What is not here cannot be invoked. */
            tools: string[];
            budget: components["schemas"]["Budget"];
            triggers?: components["schemas"]["AgentTrigger"][];
            publishedBy?: string;
            /** Format: date-time */
            publishedAt: string;
            /** @description Whether this is the newest published version of the agent. */
            latest: boolean;
            /** @description Absent when the agent has never run, which is a different thing from having run and finished. */
            activity?: components["schemas"]["AgentActivity"] | null;
        };
        /** @description How the agent has been doing, aggregated from its runs. An agent has no state of its own to report — there is no autonomy stage yet — so what an operator sees is a fact about its runs. */
        AgentActivity: {
            /** Format: int64 */
            runs: number;
            /** Format: int64 */
            finished: number;
            /**
             * Format: int64
             * @description Runs stopped for a person — awaiting approval or parked.
             */
            waiting: number;
            /** Format: int64 */
            costMicros: number;
            lastPhase?: components["schemas"]["Phase"];
            /** Format: date-time */
            lastRunAt?: string;
        };
        AgentTrigger: {
            /** @enum {string} */
            type: "cron" | "webhook" | "event";
            schedule?: string;
            path?: string;
            event?: string;
        };
        /** @description The ceilings a run is checked against. Every dimension is enforced at the Gate. */
        Budget: {
            /** Format: int64 */
            micros?: number;
            /** Format: int64 */
            tokens?: number;
            /** Format: int64 */
            toolCalls?: number;
            /** Format: int64 */
            steps?: number;
            /** Format: int64 */
            wallClockMs?: number;
        };
        RunStats: {
            /**
             * Format: int64
             * @description Runs matching the filter, not runs returned.
             */
            total: number;
            /** @description Runs per phase. A phase with no runs is absent, so "none" is distinguishable from "not measured". */
            byPhase: {
                [key: string]: number;
            };
            /**
             * Format: int64
             * @description How many runs the median was computed over.
             */
            ended: number;
            /**
             * Format: int64
             * @description Median wall-clock duration of runs that ended. Absent when none have.
             */
            medianDurationMs?: number | null;
            /**
             * Format: int64
             * @description The slow tail, over the same runs as the median. On its own a
             *     median says nothing about the runs people complain about.
             */
            p95DurationMs?: number | null;
        };
        DecisionPage: {
            items: components["schemas"]["RecordedDecision"][];
        };
        RecordedDecision: {
            runId: string;
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            at: string;
            scope?: components["schemas"]["Scope"];
            agentId?: string;
            tool?: string;
            verdict: components["schemas"]["Verdict"];
            /** @description The rule that applied. The feed names it rather than a category. */
            rule?: string;
        };
        Throughput: {
            buckets: components["schemas"]["ThroughputBucket"][];
        };
        ThroughputBucket: {
            /**
             * Format: date-time
             * @description The start of the hour, in UTC.
             */
            at: string;
            /** Format: int64 */
            total: number;
            /** @description Runs per phase within the hour. A phase with none is absent. */
            byPhase: {
                [key: string]: number;
            };
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            nextCursor?: string | null;
        };
        Step: {
            /** Format: int64 */
            seq: number;
            kind: components["schemas"]["StepKind"];
            /** Format: date-time */
            at: string;
            cost?: components["schemas"]["Cost"];
            labels?: string[];
            policyHash?: string;
            /**
             * @description Kind-specific detail. Bulky content is not inlined: payloads carry
             *     a reference into object storage plus a digest, because arguments
             *     and results routinely contain personal data.
             */
            payload?: {
                [key: string]: unknown;
            };
            /** @description Hex-encoded SHA-256 sealing this step to the previous one. */
            hash: string;
        };
        StepContent: {
            /** Format: int64 */
            seq: number;
            /**
             * @description Hex-encoded SHA-256 of the content, as recorded in the step. A
             *     caller that hashes the body and gets a different value is not
             *     looking at what the chain sealed.
             */
            digest: string;
            /** @description The bytes, as text. JSON arguments arrive as a JSON string. */
            content: string;
        };
        StepPage: {
            items: components["schemas"]["Step"][];
            /** Format: int64 */
            nextSeq?: number | null;
        };
        VerifyResult: {
            valid: boolean;
            /** Format: int64 */
            stepsChecked: number;
            /**
             * Format: int64
             * @description The first step whose link failed, when valid is false.
             */
            brokenAtSeq?: number | null;
        };
        PendingApproval: {
            runId: string;
            scope?: components["schemas"]["Scope"];
            agentId?: string;
            tool: string;
            effect?: components["schemas"]["Effect"];
            /** @description The rule that required approval. The trail never says "denied by policy" — it names the rule. */
            rule?: string;
            reason?: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: int64 */
            atSeq: number;
        };
        ApprovalPage: {
            items: components["schemas"]["PendingApproval"][];
            nextCursor?: string | null;
        };
        ApprovalDecision: {
            approved: boolean;
            /**
             * Format: int64
             * @description Sequence number of the approval_requested step being answered.
             *     Required so a stale browser tab cannot approve an action that a
             *     later step already superseded.
             */
            atSeq: number;
            note?: string;
        };
        CostBucket: {
            key: string;
            cost: components["schemas"]["Cost"];
            /** Format: int64 */
            runs: number;
        };
        CostRollup: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            groupBy: string;
            total: components["schemas"]["Cost"];
            buckets: components["schemas"]["CostBucket"][];
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
        };
    };
    responses: {
        /** @description The request is malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated, but the caller does not hold the permission in this scope. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource, or it is outside the caller's scope. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        RunId: string;
        /** @description Company scope. A single value until multi-company (PRD 3.1). */
        Company: string;
        Area: string;
        /** @description Opaque cursor from the previous page. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                /** @description Return the publication history instead of the newest version of each agent. */
                allVersions?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Agent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                agentId?: string;
                phase?: components["schemas"]["Phase"];
                /** @description Only runs started at or after this instant. */
                since?: string;
                /** @description Matches the run identifier or the agent identifier. Applied where the whole set is, so a page of results is the whole answer rather than whatever happened to be loaded. */
                q?: string;
                /** @description Opaque cursor from the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRunStats: {
        parameters: {
            query?: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                agentId?: string;
                /** @description Only runs started at or after this instant. */
                since?: string;
                /**
                 * @description Only runs started before this instant. Needed to close a window:
                 *     a figure compared against another — yesterday against today — is
                 *     wrong if the earlier window has no upper bound.
                 */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregates over the matching runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getThroughput: {
        parameters: {
            query?: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                agentId?: string;
                since?: string;
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The buckets, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Throughput"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                agentId?: string;
                /** @description Only decisions taken at or after this instant. */
                since?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRunSteps: {
        parameters: {
            query?: {
                /** @description First sequence number to return. Defaults to 1. */
                fromSeq?: number;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of steps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getStepContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                /** @description The step's sequence number. */
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The referenced content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepContent"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                /** @description Opaque cursor from the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending approvals, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPage"];
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description The decision was recorded and the run resumed or ended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The run has no pending approval, or it already expired. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCostRollup: {
        parameters: {
            query: {
                /** @description Company scope. A single value until multi-company (PRD 3.1). */
                company?: components["parameters"]["Company"];
                area?: components["parameters"]["Area"];
                from: string;
                to: string;
                groupBy?: "company" | "area" | "agent" | "day";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rollup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostRollup"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tool catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tool"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    classifyTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                toolId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    effect: components["schemas"]["Effect"];
                    /** @description Whether results carry data the platform did not author. Reading one taints the run. */
                    untrusted?: boolean;
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description The ruling is recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configured integrations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        mcpServers: components["schemas"]["MCPServer"][];
                        providers: components["schemas"]["ModelProvider"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Namespaces the tools this server offers. */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    command: string;
                    args?: string[];
                    /** @default true */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description The server is configured. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putModelProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "anthropic" | "openai_compatible";
                    baseUrl: string;
                    /** @description Sealed in the vault on arrival and never returned. Omit it to keep the stored credential — changing a base URL should not require re-entering a key. */
                    apiKey?: string;
                    /** @default true */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description The provider is configured. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteModelProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The provider is removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listBudgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured ceilings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ScopeBudget"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `installation`, a company id, or `company/area`. */
                scope: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    period: "daily" | "monthly";
                    /** Format: int64 */
                    micros?: number;
                    /** Format: int64 */
                    tokens?: number;
                    /** Format: int64 */
                    toolCalls?: number;
                    /** Format: int64 */
                    steps?: number;
                    /** Format: int64 */
                    wallClockMs?: number;
                    /** @default true */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description The ceiling is set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scope: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ceiling is removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminEvents: {
        parameters: {
            query?: {
                /** @description Read the trail backwards from one object. */
                target?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrative events, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminEvent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
