-- Where a webhook's path and its secret live.
--
-- One row per declared path. The path comes from the agent's specification;
-- the secret does not — it is generated by an operator from the console and
-- stored only as a hash, so a database dump does not hand somebody the ability
-- to make agents run.
--
-- A trigger with no secret cannot fire. That is deliberate: a declared webhook
-- that accepted anything until somebody got round to configuring it would be
-- an open door with an agent behind it.
create table if not exists webhook_triggers (
    path        text        not null primary key,
    agent_id    text        not null,
    company_id  text        not null default '',
    area_id     text        not null default '',
    secret_hash bytea,
    rotated_by  text        not null default '',
    rotated_at  timestamptz,
    created_at  timestamptz not null default now()
);

create index if not exists webhook_triggers_agent_idx
    on webhook_triggers (agent_id);
